### ISSUE TITLE
关于proxy.php的问题

### ISSUE THREAD

**Issue by EAimTY** [slime7/dmmlogin#2]
您好，请问`proxy.php`文件中的IP和端口具体是指什么？是VPS的IP与Web Server的端口吗？还是舰C服务器的？如果是VPS本机的那么是否需要在防火墙中放行设置的端口？
另外，readme中的`proxy.php`误写成`poxy.php`了…

**Comment by slime7** [comment]
是个http代理的ip和端口。这个是给没有日本服务器的用的，如果你把这个项目放在你vps上就不需要用到这个了。你要是放自己电脑运行，你可以设为你平时玩游戏用的那个代理软件的端口，ip一般就是127.0.0.1或者localhost了。

**Comment by EAimTY** [comment]
谢谢😁但还有一个问题：当在站点上部署SSL后使用include swf模式游戏Chrome会提示不安全，貌似是因为引用了“不安全”的内容，请问是否有解决方法？
另外，设置nginx将所有request rewrite到index.php是否更加安全？

**Comment by slime7** [comment]
include模式因为Mix Content没办法解，这个模式用poi等工具玩也不会自动识别到flash窗口。我一般直接用第二个登录的，只是poi不给个后退按钮，f5不方便，要把登录页设为主页然后右键点主页按钮……
你部署了SSL，要不要rewrite都一样吧（不确定）。
